version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: livraria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      target: run
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/livraria
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
  
  tests:
    build:
      context: .
      target: test
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: test
    command: ["./mvnw", "test"]

volumes:
  postgres-data:
