package com.livraria.application.config;

import com.livraria.domain.model.Book;
import com.livraria.domain.ports.BookRepositoryPort;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Component
@RequiredArgsConstructor
public class DataLoader implements ApplicationRunner {

    private final BookRepositoryPort bookRepository;

    @Override
    public void run(ApplicationArguments args) {
        if (bookRepository.count() > 0)
            return;

        Map<String, Integer> titleCounts = new HashMap<>();
        List<Book> livrosOriginais = List.of(
                new Book(null, "Dom Casmurro", "Machado de Assis",
                        "Romance clássico brasileiro que narra a história de Bento Santiago e seu amor por Capitu, explorando temas como ciúme e traição.",
                        "Romance"),
                new Book(null, "O Alquimista", "Paulo Coelho",
                        "A jornada de Santiago, um jovem pastor andaluz, em busca de seu sonho e significado da vida, com muita espiritualidade e aprendizado.",
                        "Ficção"),
                new Book(null, "1984", "George Orwell",
                        "Distopia que mostra um regime totalitário e vigilância constante, expondo o controle do Estado sobre a vida das pessoas.",
                        "Ficção Científica"),
                new Book(null, "Grande Sertão: Veredas", "João Guimarães Rosa",
                        "Narrativa complexa do jagunço Riobaldo, que mistura realismo e misticismo na região do sertão brasileiro.",
                        "Romance"),
                new Book(null, "O Pequeno Príncipe", "Antoine de Saint-Exupéry",
                        "Uma fábula poética que fala sobre amizade, amor e a importância das coisas invisíveis aos olhos.",
                        "Infantil"),
                new Book(null, "Memórias Póstumas de Brás Cubas", "Machado de Assis",
                        "Narrado por um defunto, o livro critica a sociedade brasileira do século XIX com ironia e pessimismo.",
                        "Romance"),
                new Book(null, "A Revolução dos Bichos", "George Orwell",
                        "Fábula satírica que representa uma revolução social e política na fazenda dos animais, crítica ao totalitarismo.",
                        "Ficção"),
                new Book(null, "O Cortiço", "Aluísio Azevedo",
                        "Romance naturalista que retrata a vida difícil e conflituosa em um cortiço no Rio de Janeiro do século XIX.",
                        "Romance"),
                new Book(null, "Cem Anos de Solidão", "Gabriel García Márquez",
                        "Saga da família Buendía na cidade fictícia de Macondo, cheia de realismo mágico e história latino-americana.",
                        "Romance"),
                new Book(null, "O Morro dos Ventos Uivantes", "Emily Brontë",
                        "História intensa de amor e vingança na sombria fazenda de Wuthering Heights, cheia de paixões e tragédias.",
                        "Romance"),
                new Book(null, "Ensaio Sobre a Cegueira", "José Saramago",
                        "Um misterioso surto de cegueira atinge uma cidade, mostrando o colapso da sociedade e a luta pela sobrevivência.",
                        "Ficção"),
                new Book(null, "A Metamorfose", "Franz Kafka",
                        "Gregor Samsa acorda transformado em um inseto gigante, explorando temas de alienação e existência.",
                        "Ficção"),
                new Book(null, "O Hobbit", "J.R.R. Tolkien",
                        "A aventura de Bilbo Bolseiro, um hobbit que embarca em uma jornada para recuperar um tesouro guardado por um dragão.",
                        "Fantasia"),
                new Book(null, "Dom Quixote", "Miguel de Cervantes",
                        "Clássico da literatura espanhola que satiriza os romances de cavalaria, narrando as aventuras de Dom Quixote e seu escudeiro.",
                        "Romance"),
                new Book(null, "O Senhor dos Anéis", "J.R.R. Tolkien",
                        "Épica saga de fantasia sobre a luta para destruir o Um Anel e salvar a Terra Média do mal.",
                        "Fantasia"),
                new Book(null, "O Processo", "Franz Kafka",
                        "Um homem é preso e julgado por um crime desconhecido, refletindo sobre burocracia e justiça opressiva.",
                        "Ficção"),
                new Book(null, "A Ilha do Tesouro", "Robert Louis Stevenson",
                        "Clássica aventura de piratas, com mapas do tesouro, traições e batalhas pelo ouro escondido.",
                        "Aventura"),
                new Book(null, "O Médico e o Monstro", "Robert Louis Stevenson",
                        "Exploração dos lados opostos da natureza humana através do Dr. Jekyll e seu alter ego, Mr. Hyde.",
                        "Terror"),
                new Book(null, "Os Lusíadas", "Luís de Camões",
                        "Poema épico que celebra as descobertas portuguesas e o espírito navegante da época dos Descobrimentos.",
                        "Poesia"),
                new Book(null, "O Código Da Vinci", "Dan Brown",
                        "Um mistério envolvendo símbolos antigos, sociedades secretas e uma corrida para desvendar segredos que podem abalar o mundo.",
                        "Suspense"),

                new Book(null, "A Menina que Roubava Livros", "Markus Zusak",
                        "Narrado pela Morte, conta a história de Liesel, uma garota que encontra consolo nos livros durante a Segunda Guerra Mundial.",
                        "Drama"),
                new Book(null, "Harry Potter e a Pedra Filosofal", "J.K. Rowling",
                        "O início das aventuras de Harry Potter, um jovem bruxo que descobre seu destino e frequenta uma escola de magia.",
                        "Fantasia"),
                new Book(null, "O Caçador de Pipas", "Khaled Hosseini",
                        "Um drama emocionante sobre amizade, traição e redenção ambientado no Afeganistão.", "Drama"),
                new Book(null, "Crepúsculo", "Stephenie Meyer",
                        "Romance entre uma humana e um vampiro, com conflitos sobrenaturais e dilemas amorosos.",
                        "Romance"),
                new Book(null, "O Diário de Anne Frank", "Anne Frank",
                        "Relatos reais da jovem Anne Frank enquanto se esconde dos nazistas durante a Segunda Guerra Mundial.",
                        "Biografia"),
                new Book(null, "Jogos Vorazes", "Suzanne Collins",
                        "Em um futuro distópico, jovens são forçados a lutar pela sobrevivência em um reality show mortal.",
                        "Ficção Científica"),
                new Book(null, "O Senhor das Moscas", "William Golding",
                        "Um grupo de crianças fica preso numa ilha deserta e precisa lidar com a luta pelo poder e a natureza humana.",
                        "Drama"),
                new Book(null, "A Cabana", "William P. Young",
                        "Um homem lida com a perda e encontra fé e esperança em uma cabana misteriosa.", "Drama"),
                new Book(null, "O Pequeno Príncipe", "Antoine de Saint-Exupéry",
                        "Uma fábula sobre a importância do amor e da amizade, narrada por um piloto que encontra um príncipe em um planeta distante.",
                        "Infantil"),
                new Book(null, "O Morro dos Ventos Uivantes", "Emily Brontë",
                        "História intensa de amor e vingança na sombria fazenda de Wuthering Heights.", "Romance"),
                new Book(null, "O Velho e o Mar", "Ernest Hemingway",
                        "A luta épica de um velho pescador cubano para capturar um enorme marlim.", "Ficção"),
                new Book(null, "A Revolução dos Bichos", "George Orwell",
                        "Fábula que critica regimes totalitários através de uma revolução animal na fazenda.",
                        "Ficção"),
                new Book(null, "O Apanhador no Campo de Centeio", "J.D. Salinger",
                        "Narrativa em primeira pessoa de Holden Caulfield, um jovem problemático em Nova York.",
                        "Romance"),
                new Book(null, "O Sol é para Todos", "Harper Lee",
                        "Drama sobre racismo e injustiça no sul dos Estados Unidos na década de 1930.", "Drama"),
                new Book(null, "O Hobbit", "J.R.R. Tolkien",
                        "A aventura de Bilbo Bolseiro, um hobbit que embarca em uma jornada para recuperar um tesouro guardado por um dragão.",
                        "Fantasia"),
                new Book(null, "Moby Dick", "Herman Melville", "Obcecada caça à baleia branca pelo capitão Ahab.",
                        "Aventura"),
                new Book(null, "O Conde de Monte Cristo", "Alexandre Dumas",
                        "História de vingança e justiça do jovem Edmond Dantès.", "Aventura"),
                new Book(null, "O Senhor dos Anéis", "J.R.R. Tolkien", "Épica saga sobre a destruição do Um Anel.",
                        "Fantasia"),
                new Book(null, "O Perfume", "Patrick Süskind",
                        "Narrativa de um homem com olfato excepcional que se torna assassino em busca do perfume perfeito.",
                        "Suspense"),
                new Book(null, "O Lobo da Estepe", "Hermann Hesse",
                        "Conflito interior de um homem dividido entre a razão e seus instintos.", "Ficção"),
                new Book(null, "O Pequeno Príncipe", "Antoine de Saint-Exupéry",
                        "História poética sobre amizade e amor.", "Infantil"),
                new Book(null, "Crime e Castigo", "Fiódor Dostoiévski",
                        "Drama psicológico de um jovem estudante que comete um assassinato.", "Drama"),
                new Book(null, "O Processo", "Franz Kafka",
                        "Um homem é preso sem saber o motivo e enfrenta uma burocracia opressora.", "Ficção"),
                new Book(null, "A Menina do Vale", "Bel Pesce",
                        "História inspiradora de uma jovem empreendedora brasileira.", "Biografia"),
                new Book(null, "O Guia do Mochileiro das Galáxias", "Douglas Adams",
                        "Comédia de ficção científica sobre as aventuras no espaço.", "Ficção Científica"),
                new Book(null, "O Nome da Rosa", "Umberto Eco",
                        "Mistério em um mosteiro medieval com assassinatos e intrigas.", "Suspense"),
                new Book(null, "A Menina que Roubava Livros", "Markus Zusak",
                        "História de uma menina que encontra esperança nos livros durante a guerra.", "Drama"),
                new Book(null, "O Sol Também se Levanta", "Ernest Hemingway",
                        "Retrato da geração perdida após a Primeira Guerra Mundial.", "Romance"),
                new Book(null, "O Pequeno Príncipe", "Antoine de Saint-Exupéry",
                        "Uma fábula poética e filosófica sobre a vida e a amizade.", "Infantil"),
                new Book(null, "O Senhor dos Anéis: As Duas Torres", "J.R.R. Tolkien",
                        "Continuação da saga na Terra Média, com batalhas épicas.", "Fantasia"),
                new Book(null, "O Senhor dos Anéis: O Retorno do Rei", "J.R.R. Tolkien",
                        "Conclusão da trilogia com a batalha final contra o mal.", "Fantasia"),
                new Book(null, "O Alquimista", "Paulo Coelho", "História de autodescoberta e sonhos.", "Ficção"),
                new Book(null, "Dom Casmurro", "Machado de Assis",
                        "Clássico da literatura brasileira sobre ciúme e traição.", "Romance"),
                new Book(null, "Grande Sertão: Veredas", "João Guimarães Rosa",
                        "Narrativa sobre o sertão e seus mitos.", "Romance"),
                new Book(null, "Memórias Póstumas de Brás Cubas", "Machado de Assis",
                        "Crítica à sociedade brasileira narrada por um defunto.", "Romance"),
                new Book(null, "O Cortiço", "Aluísio Azevedo", "Retrato do cotidiano no Rio de Janeiro do século XIX.",
                        "Romance"),
                new Book(null, "Cem Anos de Solidão", "Gabriel García Márquez", "Família Buendía e realismo mágico.",
                        "Romance"),
                new Book(null, "O Morro dos Ventos Uivantes", "Emily Brontë", "Amor e vingança numa fazenda.",
                        "Romance"),
                new Book(null, "Ensaio Sobre a Cegueira", "José Saramago",
                        "Colapso social após uma epidemia de cegueira.", "Ficção"),
                new Book(null, "A Metamorfose", "Franz Kafka", "Transformação e alienação de Gregor Samsa.", "Ficção"),
                new Book(null, "O Código Da Vinci", "Dan Brown", "Mistério e símbolos em busca da verdade.",
                        "Suspense"),
                new Book(null, "Harry Potter e a Câmara Secreta", "J.K. Rowling",
                        "Segunda aventura de Harry Potter em Hogwarts.", "Fantasia"),
                new Book(null, "Harry Potter e o Prisioneiro de Azkaban", "J.K. Rowling",
                        "Terceiro ano de Harry com segredos sombrios.", "Fantasia"),
                new Book(null, "Harry Potter e o Cálice de Fogo", "J.K. Rowling",
                        "Competição mágica com perigos mortais.", "Fantasia"),
                new Book(null, "Harry Potter e a Ordem da Fênix", "J.K. Rowling",
                        "Luta contra as forças do mal em Hogwarts.", "Fantasia"),
                new Book(null, "Harry Potter e o Enigma do Príncipe", "J.K. Rowling",
                        "Segredos do passado de Voldemort.", "Fantasia"),
                new Book(null, "Harry Potter e as Relíquias da Morte", "J.K. Rowling",
                        "Batalha final contra Voldemort.", "Fantasia"),
                new Book(null, "O Caçador de Pipas", "Khaled Hosseini", "Amizade e redenção no Afeganistão.", "Drama"),
                new Book(null, "Jogos Vorazes", "Suzanne Collins", "Luta pela sobrevivência em um reality show.",
                        "Ficção Científica"),
                new Book(null, "Divergente", "Veronica Roth",
                        "Sociedade dividida em facções e uma jovem que desafia o sistema.", "Ficção Científica"),
                new Book(null, "Maze Runner", "James Dashner", "Jovens presos num labirinto misterioso.",
                        "Ficção Científica"),
                new Book(null, "Percy Jackson e os Olimpianos", "Rick Riordan",
                        "Jovem semideus em aventuras mitológicas.", "Fantasia"),
                new Book(null, "O Senhor das Moscas", "William Golding",
                        "Conflito e sobrevivência de crianças numa ilha.", "Drama"),
                new Book(null, "O Morro dos Ventos Uivantes", "Emily Brontë", "História de amor e vingança.",
                        "Romance"),
                new Book(null, "A Cabana", "William P. Young", "Encontro com a fé e o perdão.", "Drama"),
                new Book(null, "O Pequeno Príncipe", "Antoine de Saint-Exupéry", "Fábula poética sobre a vida.",
                        "Infantil"),
                new Book(null, "Dom Quixote", "Miguel de Cervantes", "Aventuras de um cavaleiro delirante.", "Romance"),
                new Book(null, "O Apanhador no Campo de Centeio", "J.D. Salinger", "Jovem problemático em Nova York.",
                        "Romance"),
                new Book(null, "O Sol é para Todos", "Harper Lee", "Luta contra o racismo.", "Drama"),
                new Book(null, "Moby Dick", "Herman Melville", "Caça obsessiva à baleia branca.", "Aventura"),
                new Book(null, "O Conde de Monte Cristo", "Alexandre Dumas", "Vingança e justiça.", "Aventura"),
                new Book(null, "O Perfume", "Patrick Süskind", "Obssessão pelo perfume perfeito.", "Suspense"),
                new Book(null, "O Lobo da Estepe", "Hermann Hesse", "Conflito interior humano.", "Ficção"),
                new Book(null, "Crime e Castigo", "Fiódor Dostoiévski", "Drama psicológico.", "Drama"),
                new Book(null, "O Guia do Mochileiro das Galáxias", "Douglas Adams", "Comédia no espaço.",
                        "Ficção Científica"),
                new Book(null, "O Nome da Rosa", "Umberto Eco", "Mistério em um mosteiro.", "Suspense"),
                new Book(null, "A Menina do Vale", "Bel Pesce", "História de sucesso empreendedora.", "Biografia"),
                new Book(null, "A Cabana", "William P. Young", "Encontro com a fé e o perdão.", "Drama"),
                new Book(null, "O Pequeno Príncipe", "Antoine de Saint-Exupéry", "Fábula poética sobre a vida.",
                        "Infantil"),
                new Book(null, "Dom Quixote", "Miguel de Cervantes", "Aventuras de um cavaleiro delirante.", "Romance"),
                new Book(null, "O Apanhador no Campo de Centeio", "J.D. Salinger", "Jovem problemático em Nova York.",
                        "Romance"),
                new Book(null, "O Sol é para Todos", "Harper Lee", "Luta contra o racismo.", "Drama"),
                new Book(null, "Moby Dick", "Herman Melville", "Caça obsessiva à baleia branca.", "Aventura"),
                new Book(null, "O Conde de Monte Cristo", "Alexandre Dumas", "Vingança e justiça.", "Aventura"),
                new Book(null, "O Perfume", "Patrick Süskind", "Obssessão pelo perfume perfeito.", "Suspense"),
                new Book(null, "O Lobo da Estepe", "Hermann Hesse", "Conflito interior humano.", "Ficção"),
                new Book(null, "Crime e Castigo", "Fiódor Dostoiévski", "Drama psicológico.", "Drama"),
                new Book(null, "O Guia do Mochileiro das Galáxias", "Douglas Adams", "Comédia no espaço.",
                        "Ficção Científica"),
                new Book(null, "O Nome da Rosa", "Umberto Eco", "Mistério em um mosteiro.", "Suspense"),
                new Book(null, "A Menina do Vale", "Bel Pesce", "História de sucesso empreendedora.", "Biografia"));

        List<Book> livrosSemDuplicatas = new ArrayList<>();

        for (Book book : livrosOriginais) {
            String originalTitle = book.getTitle();
            int count = titleCounts.getOrDefault(originalTitle, 0);

            String titleWithSuffix = count == 0 ? originalTitle : originalTitle + " (" + count + ")";
            titleCounts.put(originalTitle, count + 1);

            livrosSemDuplicatas.add(new Book(
                    null,
                    titleWithSuffix,
                    book.getAuthor(),
                    book.getDescription(),
                    book.getGenre()));
        }

        livrosSemDuplicatas.forEach(bookRepository::save);
    }
}
